name: Issue management

on:
  issues:
    types: [opened, assigned, closed]

# map fields with customized labels
env:
  todo: Todo
  assigned: Assigned
  done: Done

  project-owner: 'devops-actions'
  project-number: 2

jobs:
  issue-created:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'opened' && github.repository == 'devops-actions/demo-actions'
    steps:
    
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db
        with:
          application_id: ${{ secrets.GH_APPLICATION_ID }}
          application_private_key: ${{ secrets.GH_APPLICATION_PRIVATE_KEY }}
          
      - uses: monry/actions-add-issue-to-project@774e1a9754da6cc70b5b2648cec7d53dea93211d
        id: add-issue-to-project
        with:
          # Personal Access Token that with `repo`, `org:read` and `org:write` are granted.
          github-token: ${{ steps.get_workflow_token.outputs.token }}
          project-owner: ${{ env.project-owner }}
          project-number: ${{ env.project-number }}
          issue-id: ${{ github.event.issue.node_id }}

      - name: Moved issue to ${{ env.todo }}
        uses: leonsteinhaeuser/project-beta-automations@d1c1261558118c0876fdb2b57a649303925e5a70
        with:
          gh_token: ${{ steps.get_workflow_token.outputs.token }}
          organization: ${{ env.project-owner }}
          project_id: ${{ env.project-number }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.todo }} # Target status

  issue-assigned:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'assigned' && github.repository == 'devops-actions/demo-actions'
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db
        with:
          application_id: ${{ secrets.GH_APPLICATION_ID }}
          application_private_key: ${{ secrets.GH_APPLICATION_PRIVATE_KEY }}
      
      - name: Move issue to ${{ env.assigned }}
        uses: leonsteinhaeuser/project-beta-automations@d1c1261558118c0876fdb2b57a649303925e5a70
        with:
          gh_token: ${{ steps.get_workflow_token.outputs.token }}
          organization: ${{ env.project-owner }}
          project_id: ${{ env.project-number }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.assigned }} # Target status

  issue-closed:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'closed' && github.repository == 'devops-actions/demo-actions'
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db
        with:
          application_id: ${{ secrets.GH_APPLICATION_ID }}
          application_private_key: ${{ secrets.GH_APPLICATION_PRIVATE_KEY }}
      
      - name: Move issue to ${{ env.done }}
        uses: leonsteinhaeuser/project-beta-automations@d1c1261558118c0876fdb2b57a649303925e5a70
        with:
          gh_token: ${{ steps.get_workflow_token.outputs.token }}
          organization: ${{ env.project-owner }}
          project_id: ${{ env.project-number }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.done }} # Target status
